service: graphs.agg_router:Frontend
name: frontend
version: p2cq43q7kc6evmwb
bentoml_version: 1.4.8
configFilePath: /configs/agg_router.yaml
creation_time: '2025-04-22T08:05:05.091953+00:00'
labels: {}
models: []
entry_service: Frontend
services:
- name: Frontend
  service: ''
  models: []
  dependencies:
  - service: Processor
  config:
    resources:
      cpu: '10'
      memory: 20Gi
    workers: 1
    dynamo:
      enabled: false
      name: Frontend
      namespace: default
- name: Processor
  service: ''
  models: []
  dependencies:
  - service: Router
  config:
    resources:
      cpu: '10'
      memory: 20Gi
    workers: 1
    dynamo:
      enabled: true
      name: Processor
      namespace: dynamo
- name: Router
  service: ''
  models: []
  dependencies:
  - service: VllmWorker
  config:
    resources:
      cpu: '10'
      memory: 20Gi
    workers: 1
    dynamo:
      enabled: true
      name: Router
      namespace: dynamo
- name: VllmWorker
  service: ''
  models: []
  dependencies: []
  config:
    resources:
      gpu: 1
      cpu: '10'
      memory: 20Gi
    workers: 1
    dynamo:
      enabled: true
      name: VllmWorker
      namespace: dynamo
envs: []
schema:
  name: Frontend
  type: service
  routes: []
args: {}
spec: 2
image:
  base_image: dekaregistry.cloudeka.id/cloudeka-system/dynamo-base:latest-vllm
  python_version: '3.11'
  commands: []
  python_requirements: '--index-url https://pypi.org/simple


    a2wsgi==1.10.8

    aiohappyeyeballs==2.6.1

    aiohttp==3.11.18

    aiosignal==1.3.2

    aiosqlite==0.21.0

    annotated-types==0.7.0

    anyio==4.9.0

    appdirs==1.4.4

    asgiref==3.8.1

    attrs==25.3.0

    bentoml==1.4.8

    cattrs==23.1.2

    certifi==2025.1.31

    click==8.1.8

    click-option-group==0.5.7

    cloudpickle==3.1.1

    deprecated==1.2.18

    frozenlist==1.6.0

    fs==2.4.16

    h11==0.14.0

    httpcore==1.0.8

    httpx==0.28.1

    httpx-ws==0.7.2

    idna==3.10

    importlib-metadata==8.6.1

    jinja2==3.1.6

    kantoku==0.18.3

    markdown-it-py==3.0.0

    markupsafe==3.0.2

    mdurl==0.1.2

    multidict==6.4.3

    numpy==2.2.5

    nvidia-ml-py==12.570.86

    opentelemetry-api==1.32.1

    opentelemetry-instrumentation==0.53b1

    opentelemetry-instrumentation-aiohttp-client==0.53b1

    opentelemetry-instrumentation-asgi==0.53b1

    opentelemetry-sdk==1.32.1

    opentelemetry-semantic-conventions==0.53b1

    opentelemetry-util-http==0.53b1

    packaging==25.0

    pathspec==0.12.1

    pip-requirements-parser==32.0.1

    prometheus-client==0.21.1

    prompt-toolkit==3.0.51

    propcache==0.3.1

    psutil==7.0.0

    pydantic==2.11.3

    pydantic-core==2.33.1

    pygments==2.19.1

    pyparsing==3.2.3

    python-dateutil==2.9.0.post0

    python-dotenv==1.1.0

    python-json-logger==3.3.0

    python-multipart==0.0.20

    pyyaml==6.0.2

    pyzmq==26.4.0

    questionary==2.1.0

    rich==14.0.0

    schema==0.7.7

    setuptools==79.0.0

    simple-di==0.1.5

    six==1.17.0

    sniffio==1.3.1

    starlette==0.46.2

    tomli-w==1.2.0

    tornado==6.4.2

    typing-extensions==4.13.2

    typing-inspection==0.4.0

    uvicorn==0.34.2

    watchfiles==1.0.5

    wcwidth==0.2.13

    wrapt==1.17.2

    wsproto==1.2.0

    yarl==1.20.0

    zipp==3.21.0

    '
  post_commands: []

